name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      id: make_install
      run: |
        make install
    
    - name: Format code with black
      id: make_format
      run: |
        make format
    - name: Lint with ruff
      id: make_lint
      run: |
        make lint

    - name: Test with pytest
      id: make_test
      run: |
        make test
    - name: Test nbval
      id: make_nbtest
      run: |
        make nbtest

    - name: Generate Markdown
      id: gen_markdown
      run: |
        python3 markdownGenerater.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "nicholas.conterno@duke.edu"
        git config --global user.name "nicholasconterno"
        git add generated_markdown.md histogram.png
        git commit -m "Add generated markdown and histogram" || echo "No changes to commit"
        git push
